/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the StreamStartedEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StreamStartedEvent{}

// StreamStartedEvent struct for StreamStartedEvent
type StreamStartedEvent struct {
		Id *string `json:"id,omitempty"`
}

// NewStreamStartedEvent instantiates a new StreamStartedEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamStartedEvent() *StreamStartedEvent {
	this := StreamStartedEvent{}
	return &this
}

// NewStreamStartedEventWithDefaults instantiates a new StreamStartedEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamStartedEventWithDefaults() *StreamStartedEvent {
	this := StreamStartedEvent{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *StreamStartedEvent) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamStartedEvent) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *StreamStartedEvent) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *StreamStartedEvent) SetId(v string) {
	o.Id = &v
}

func (o StreamStartedEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StreamStartedEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableStreamStartedEvent struct {
	value *StreamStartedEvent
	isSet bool
}

func (v NullableStreamStartedEvent) Get() *StreamStartedEvent {
	return v.value
}

func (v *NullableStreamStartedEvent) Set(val *StreamStartedEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamStartedEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamStartedEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamStartedEvent(val *StreamStartedEvent) *NullableStreamStartedEvent {
	return &NullableStreamStartedEvent{value: val, isSet: true}
}

func (v NullableStreamStartedEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamStartedEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


