/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateStreamTopicsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateStreamTopicsRequest{}

// UpdateStreamTopicsRequest Adding and removing topics can both be supplied in the same request, allowing for simultaneous changes. overwrite_topics will take precedence, and if set, then the add/remove topics are ignored. The stream_id is required.
type UpdateStreamTopicsRequest struct {
		Modify *ModifyTopics `json:"modify,omitempty"`
		Overwrite *OverwriteTopics `json:"overwrite,omitempty"`
		StreamId *string `json:"streamId,omitempty"`
}

// NewUpdateStreamTopicsRequest instantiates a new UpdateStreamTopicsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateStreamTopicsRequest() *UpdateStreamTopicsRequest {
	this := UpdateStreamTopicsRequest{}
	return &this
}

// NewUpdateStreamTopicsRequestWithDefaults instantiates a new UpdateStreamTopicsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateStreamTopicsRequestWithDefaults() *UpdateStreamTopicsRequest {
	this := UpdateStreamTopicsRequest{}
	return &this
}

// GetModify returns the Modify field value if set, zero value otherwise.
func (o *UpdateStreamTopicsRequest) GetModify() ModifyTopics {
	if o == nil || IsNil(o.Modify) {
		var ret ModifyTopics
		return ret
	}
	return *o.Modify
}

// GetModifyOk returns a tuple with the Modify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateStreamTopicsRequest) GetModifyOk() (*ModifyTopics, bool) {
	if o == nil || IsNil(o.Modify) {
		return nil, false
	}
	return o.Modify, true
}

// HasModify returns a boolean if a field has been set.
func (o *UpdateStreamTopicsRequest) HasModify() bool {
	if o != nil && !IsNil(o.Modify) {
		return true
	}

	return false
}

// SetModify gets a reference to the given ModifyTopics and assigns it to the Modify field.
func (o *UpdateStreamTopicsRequest) SetModify(v ModifyTopics) {
	o.Modify = &v
}

// GetOverwrite returns the Overwrite field value if set, zero value otherwise.
func (o *UpdateStreamTopicsRequest) GetOverwrite() OverwriteTopics {
	if o == nil || IsNil(o.Overwrite) {
		var ret OverwriteTopics
		return ret
	}
	return *o.Overwrite
}

// GetOverwriteOk returns a tuple with the Overwrite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateStreamTopicsRequest) GetOverwriteOk() (*OverwriteTopics, bool) {
	if o == nil || IsNil(o.Overwrite) {
		return nil, false
	}
	return o.Overwrite, true
}

// HasOverwrite returns a boolean if a field has been set.
func (o *UpdateStreamTopicsRequest) HasOverwrite() bool {
	if o != nil && !IsNil(o.Overwrite) {
		return true
	}

	return false
}

// SetOverwrite gets a reference to the given OverwriteTopics and assigns it to the Overwrite field.
func (o *UpdateStreamTopicsRequest) SetOverwrite(v OverwriteTopics) {
	o.Overwrite = &v
}

// GetStreamId returns the StreamId field value if set, zero value otherwise.
func (o *UpdateStreamTopicsRequest) GetStreamId() string {
	if o == nil || IsNil(o.StreamId) {
		var ret string
		return ret
	}
	return *o.StreamId
}

// GetStreamIdOk returns a tuple with the StreamId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateStreamTopicsRequest) GetStreamIdOk() (*string, bool) {
	if o == nil || IsNil(o.StreamId) {
		return nil, false
	}
	return o.StreamId, true
}

// HasStreamId returns a boolean if a field has been set.
func (o *UpdateStreamTopicsRequest) HasStreamId() bool {
	if o != nil && !IsNil(o.StreamId) {
		return true
	}

	return false
}

// SetStreamId gets a reference to the given string and assigns it to the StreamId field.
func (o *UpdateStreamTopicsRequest) SetStreamId(v string) {
	o.StreamId = &v
}

func (o UpdateStreamTopicsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateStreamTopicsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Modify) {
		toSerialize["modify"] = o.Modify
	}
	if !IsNil(o.Overwrite) {
		toSerialize["overwrite"] = o.Overwrite
	}
	if !IsNil(o.StreamId) {
		toSerialize["streamId"] = o.StreamId
	}
	return toSerialize, nil
}

type NullableUpdateStreamTopicsRequest struct {
	value *UpdateStreamTopicsRequest
	isSet bool
}

func (v NullableUpdateStreamTopicsRequest) Get() *UpdateStreamTopicsRequest {
	return v.value
}

func (v *NullableUpdateStreamTopicsRequest) Set(val *UpdateStreamTopicsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateStreamTopicsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateStreamTopicsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateStreamTopicsRequest(val *UpdateStreamTopicsRequest) *NullableUpdateStreamTopicsRequest {
	return &NullableUpdateStreamTopicsRequest{value: val, isSet: true}
}

func (v NullableUpdateStreamTopicsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateStreamTopicsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


