/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EstimateIntentFeeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EstimateIntentFeeResponse{}

// EstimateIntentFeeResponse struct for EstimateIntentFeeResponse
type EstimateIntentFeeResponse struct {
		Fee *int64 `json:"fee,omitempty"`
}

// NewEstimateIntentFeeResponse instantiates a new EstimateIntentFeeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEstimateIntentFeeResponse() *EstimateIntentFeeResponse {
	this := EstimateIntentFeeResponse{}
	return &this
}

// NewEstimateIntentFeeResponseWithDefaults instantiates a new EstimateIntentFeeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEstimateIntentFeeResponseWithDefaults() *EstimateIntentFeeResponse {
	this := EstimateIntentFeeResponse{}
	return &this
}

// GetFee returns the Fee field value if set, zero value otherwise.
func (o *EstimateIntentFeeResponse) GetFee() int64 {
	if o == nil || IsNil(o.Fee) {
		var ret int64
		return ret
	}
	return *o.Fee
}

// GetFeeOk returns a tuple with the Fee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EstimateIntentFeeResponse) GetFeeOk() (*int64, bool) {
	if o == nil || IsNil(o.Fee) {
		return nil, false
	}
	return o.Fee, true
}

// HasFee returns a boolean if a field has been set.
func (o *EstimateIntentFeeResponse) HasFee() bool {
	if o != nil && !IsNil(o.Fee) {
		return true
	}

	return false
}

// SetFee gets a reference to the given int64 and assigns it to the Fee field.
func (o *EstimateIntentFeeResponse) SetFee(v int64) {
	o.Fee = &v
}

func (o EstimateIntentFeeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EstimateIntentFeeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Fee) {
		toSerialize["fee"] = o.Fee
	}
	return toSerialize, nil
}

type NullableEstimateIntentFeeResponse struct {
	value *EstimateIntentFeeResponse
	isSet bool
}

func (v NullableEstimateIntentFeeResponse) Get() *EstimateIntentFeeResponse {
	return v.value
}

func (v *NullableEstimateIntentFeeResponse) Set(val *EstimateIntentFeeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEstimateIntentFeeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEstimateIntentFeeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEstimateIntentFeeResponse(val *EstimateIntentFeeResponse) *NullableEstimateIntentFeeResponse {
	return &NullableEstimateIntentFeeResponse{value: val, isSet: true}
}

func (v NullableEstimateIntentFeeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEstimateIntentFeeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


