/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModifyTopics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModifyTopics{}

// ModifyTopics struct for ModifyTopics
type ModifyTopics struct {
		AddTopics []string `json:"addTopics,omitempty"`
		RemoveTopics []string `json:"removeTopics,omitempty"`
}

// NewModifyTopics instantiates a new ModifyTopics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModifyTopics() *ModifyTopics {
	this := ModifyTopics{}
	return &this
}

// NewModifyTopicsWithDefaults instantiates a new ModifyTopics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModifyTopicsWithDefaults() *ModifyTopics {
	this := ModifyTopics{}
	return &this
}

// GetAddTopics returns the AddTopics field value if set, zero value otherwise.
func (o *ModifyTopics) GetAddTopics() []string {
	if o == nil || IsNil(o.AddTopics) {
		var ret []string
		return ret
	}
	return o.AddTopics
}

// GetAddTopicsOk returns a tuple with the AddTopics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyTopics) GetAddTopicsOk() ([]string, bool) {
	if o == nil || IsNil(o.AddTopics) {
		return nil, false
	}
	return o.AddTopics, true
}

// HasAddTopics returns a boolean if a field has been set.
func (o *ModifyTopics) HasAddTopics() bool {
	if o != nil && !IsNil(o.AddTopics) {
		return true
	}

	return false
}

// SetAddTopics gets a reference to the given []string and assigns it to the AddTopics field.
func (o *ModifyTopics) SetAddTopics(v []string) {
	o.AddTopics = v
}

// GetRemoveTopics returns the RemoveTopics field value if set, zero value otherwise.
func (o *ModifyTopics) GetRemoveTopics() []string {
	if o == nil || IsNil(o.RemoveTopics) {
		var ret []string
		return ret
	}
	return o.RemoveTopics
}

// GetRemoveTopicsOk returns a tuple with the RemoveTopics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyTopics) GetRemoveTopicsOk() ([]string, bool) {
	if o == nil || IsNil(o.RemoveTopics) {
		return nil, false
	}
	return o.RemoveTopics, true
}

// HasRemoveTopics returns a boolean if a field has been set.
func (o *ModifyTopics) HasRemoveTopics() bool {
	if o != nil && !IsNil(o.RemoveTopics) {
		return true
	}

	return false
}

// SetRemoveTopics gets a reference to the given []string and assigns it to the RemoveTopics field.
func (o *ModifyTopics) SetRemoveTopics(v []string) {
	o.RemoveTopics = v
}

func (o ModifyTopics) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModifyTopics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AddTopics) {
		toSerialize["addTopics"] = o.AddTopics
	}
	if !IsNil(o.RemoveTopics) {
		toSerialize["removeTopics"] = o.RemoveTopics
	}
	return toSerialize, nil
}

type NullableModifyTopics struct {
	value *ModifyTopics
	isSet bool
}

func (v NullableModifyTopics) Get() *ModifyTopics {
	return v.value
}

func (v *NullableModifyTopics) Set(val *ModifyTopics) {
	v.value = val
	v.isSet = true
}

func (v NullableModifyTopics) IsSet() bool {
	return v.isSet
}

func (v *NullableModifyTopics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModifyTopics(val *ModifyTopics) *NullableModifyTopics {
	return &NullableModifyTopics{value: val, isSet: true}
}

func (v NullableModifyTopics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModifyTopics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


