/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Vtxo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Vtxo{}

// Vtxo struct for Vtxo
type Vtxo struct {
		Amount *int32 `json:"amount,string,omitempty"`
		ArkTxid *string `json:"arkTxid,omitempty"`
		CommitmentTxids []string `json:"commitmentTxids,omitempty"`
		CreatedAt *int64 `json:"createdAt,string,omitempty"`
		ExpiresAt *int64 `json:"expiresAt,string,omitempty"`
		IsPreconfirmed *bool `json:"isPreconfirmed,omitempty"`
		IsSpent *bool `json:"isSpent,omitempty"`
		IsSwept *bool `json:"isSwept,omitempty"`
		IsUnrolled *bool `json:"isUnrolled,omitempty"`
		Outpoint *Outpoint `json:"outpoint,omitempty"`
		Script *string `json:"script,omitempty"`
		SettledBy *string `json:"settledBy,omitempty"`
		SpentBy *string `json:"spentBy,omitempty"`
}

// NewVtxo instantiates a new Vtxo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVtxo() *Vtxo {
	this := Vtxo{}
	return &this
}

// NewVtxoWithDefaults instantiates a new Vtxo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVtxoWithDefaults() *Vtxo {
	this := Vtxo{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *Vtxo) GetAmount() int32 {
	if o == nil || IsNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vtxo) GetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *Vtxo) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *Vtxo) SetAmount(v int32) {
	o.Amount = &v
}

// GetArkTxid returns the ArkTxid field value if set, zero value otherwise.
func (o *Vtxo) GetArkTxid() string {
	if o == nil || IsNil(o.ArkTxid) {
		var ret string
		return ret
	}
	return *o.ArkTxid
}

// GetArkTxidOk returns a tuple with the ArkTxid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vtxo) GetArkTxidOk() (*string, bool) {
	if o == nil || IsNil(o.ArkTxid) {
		return nil, false
	}
	return o.ArkTxid, true
}

// HasArkTxid returns a boolean if a field has been set.
func (o *Vtxo) HasArkTxid() bool {
	if o != nil && !IsNil(o.ArkTxid) {
		return true
	}

	return false
}

// SetArkTxid gets a reference to the given string and assigns it to the ArkTxid field.
func (o *Vtxo) SetArkTxid(v string) {
	o.ArkTxid = &v
}

// GetCommitmentTxids returns the CommitmentTxids field value if set, zero value otherwise.
func (o *Vtxo) GetCommitmentTxids() []string {
	if o == nil || IsNil(o.CommitmentTxids) {
		var ret []string
		return ret
	}
	return o.CommitmentTxids
}

// GetCommitmentTxidsOk returns a tuple with the CommitmentTxids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vtxo) GetCommitmentTxidsOk() ([]string, bool) {
	if o == nil || IsNil(o.CommitmentTxids) {
		return nil, false
	}
	return o.CommitmentTxids, true
}

// HasCommitmentTxids returns a boolean if a field has been set.
func (o *Vtxo) HasCommitmentTxids() bool {
	if o != nil && !IsNil(o.CommitmentTxids) {
		return true
	}

	return false
}

// SetCommitmentTxids gets a reference to the given []string and assigns it to the CommitmentTxids field.
func (o *Vtxo) SetCommitmentTxids(v []string) {
	o.CommitmentTxids = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Vtxo) GetCreatedAt() int64 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int64
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vtxo) GetCreatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Vtxo) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int64 and assigns it to the CreatedAt field.
func (o *Vtxo) SetCreatedAt(v int64) {
	o.CreatedAt = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *Vtxo) GetExpiresAt() int64 {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret int64
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vtxo) GetExpiresAtOk() (*int64, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *Vtxo) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given int64 and assigns it to the ExpiresAt field.
func (o *Vtxo) SetExpiresAt(v int64) {
	o.ExpiresAt = &v
}

// GetIsPreconfirmed returns the IsPreconfirmed field value if set, zero value otherwise.
func (o *Vtxo) GetIsPreconfirmed() bool {
	if o == nil || IsNil(o.IsPreconfirmed) {
		var ret bool
		return ret
	}
	return *o.IsPreconfirmed
}

// GetIsPreconfirmedOk returns a tuple with the IsPreconfirmed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vtxo) GetIsPreconfirmedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPreconfirmed) {
		return nil, false
	}
	return o.IsPreconfirmed, true
}

// HasIsPreconfirmed returns a boolean if a field has been set.
func (o *Vtxo) HasIsPreconfirmed() bool {
	if o != nil && !IsNil(o.IsPreconfirmed) {
		return true
	}

	return false
}

// SetIsPreconfirmed gets a reference to the given bool and assigns it to the IsPreconfirmed field.
func (o *Vtxo) SetIsPreconfirmed(v bool) {
	o.IsPreconfirmed = &v
}

// GetIsSpent returns the IsSpent field value if set, zero value otherwise.
func (o *Vtxo) GetIsSpent() bool {
	if o == nil || IsNil(o.IsSpent) {
		var ret bool
		return ret
	}
	return *o.IsSpent
}

// GetIsSpentOk returns a tuple with the IsSpent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vtxo) GetIsSpentOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSpent) {
		return nil, false
	}
	return o.IsSpent, true
}

// HasIsSpent returns a boolean if a field has been set.
func (o *Vtxo) HasIsSpent() bool {
	if o != nil && !IsNil(o.IsSpent) {
		return true
	}

	return false
}

// SetIsSpent gets a reference to the given bool and assigns it to the IsSpent field.
func (o *Vtxo) SetIsSpent(v bool) {
	o.IsSpent = &v
}

// GetIsSwept returns the IsSwept field value if set, zero value otherwise.
func (o *Vtxo) GetIsSwept() bool {
	if o == nil || IsNil(o.IsSwept) {
		var ret bool
		return ret
	}
	return *o.IsSwept
}

// GetIsSweptOk returns a tuple with the IsSwept field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vtxo) GetIsSweptOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSwept) {
		return nil, false
	}
	return o.IsSwept, true
}

// HasIsSwept returns a boolean if a field has been set.
func (o *Vtxo) HasIsSwept() bool {
	if o != nil && !IsNil(o.IsSwept) {
		return true
	}

	return false
}

// SetIsSwept gets a reference to the given bool and assigns it to the IsSwept field.
func (o *Vtxo) SetIsSwept(v bool) {
	o.IsSwept = &v
}

// GetIsUnrolled returns the IsUnrolled field value if set, zero value otherwise.
func (o *Vtxo) GetIsUnrolled() bool {
	if o == nil || IsNil(o.IsUnrolled) {
		var ret bool
		return ret
	}
	return *o.IsUnrolled
}

// GetIsUnrolledOk returns a tuple with the IsUnrolled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vtxo) GetIsUnrolledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsUnrolled) {
		return nil, false
	}
	return o.IsUnrolled, true
}

// HasIsUnrolled returns a boolean if a field has been set.
func (o *Vtxo) HasIsUnrolled() bool {
	if o != nil && !IsNil(o.IsUnrolled) {
		return true
	}

	return false
}

// SetIsUnrolled gets a reference to the given bool and assigns it to the IsUnrolled field.
func (o *Vtxo) SetIsUnrolled(v bool) {
	o.IsUnrolled = &v
}

// GetOutpoint returns the Outpoint field value if set, zero value otherwise.
func (o *Vtxo) GetOutpoint() Outpoint {
	if o == nil || IsNil(o.Outpoint) {
		var ret Outpoint
		return ret
	}
	return *o.Outpoint
}

// GetOutpointOk returns a tuple with the Outpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vtxo) GetOutpointOk() (*Outpoint, bool) {
	if o == nil || IsNil(o.Outpoint) {
		return nil, false
	}
	return o.Outpoint, true
}

// HasOutpoint returns a boolean if a field has been set.
func (o *Vtxo) HasOutpoint() bool {
	if o != nil && !IsNil(o.Outpoint) {
		return true
	}

	return false
}

// SetOutpoint gets a reference to the given Outpoint and assigns it to the Outpoint field.
func (o *Vtxo) SetOutpoint(v Outpoint) {
	o.Outpoint = &v
}

// GetScript returns the Script field value if set, zero value otherwise.
func (o *Vtxo) GetScript() string {
	if o == nil || IsNil(o.Script) {
		var ret string
		return ret
	}
	return *o.Script
}

// GetScriptOk returns a tuple with the Script field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vtxo) GetScriptOk() (*string, bool) {
	if o == nil || IsNil(o.Script) {
		return nil, false
	}
	return o.Script, true
}

// HasScript returns a boolean if a field has been set.
func (o *Vtxo) HasScript() bool {
	if o != nil && !IsNil(o.Script) {
		return true
	}

	return false
}

// SetScript gets a reference to the given string and assigns it to the Script field.
func (o *Vtxo) SetScript(v string) {
	o.Script = &v
}

// GetSettledBy returns the SettledBy field value if set, zero value otherwise.
func (o *Vtxo) GetSettledBy() string {
	if o == nil || IsNil(o.SettledBy) {
		var ret string
		return ret
	}
	return *o.SettledBy
}

// GetSettledByOk returns a tuple with the SettledBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vtxo) GetSettledByOk() (*string, bool) {
	if o == nil || IsNil(o.SettledBy) {
		return nil, false
	}
	return o.SettledBy, true
}

// HasSettledBy returns a boolean if a field has been set.
func (o *Vtxo) HasSettledBy() bool {
	if o != nil && !IsNil(o.SettledBy) {
		return true
	}

	return false
}

// SetSettledBy gets a reference to the given string and assigns it to the SettledBy field.
func (o *Vtxo) SetSettledBy(v string) {
	o.SettledBy = &v
}

// GetSpentBy returns the SpentBy field value if set, zero value otherwise.
func (o *Vtxo) GetSpentBy() string {
	if o == nil || IsNil(o.SpentBy) {
		var ret string
		return ret
	}
	return *o.SpentBy
}

// GetSpentByOk returns a tuple with the SpentBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vtxo) GetSpentByOk() (*string, bool) {
	if o == nil || IsNil(o.SpentBy) {
		return nil, false
	}
	return o.SpentBy, true
}

// HasSpentBy returns a boolean if a field has been set.
func (o *Vtxo) HasSpentBy() bool {
	if o != nil && !IsNil(o.SpentBy) {
		return true
	}

	return false
}

// SetSpentBy gets a reference to the given string and assigns it to the SpentBy field.
func (o *Vtxo) SetSpentBy(v string) {
	o.SpentBy = &v
}

func (o Vtxo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Vtxo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.ArkTxid) {
		toSerialize["arkTxid"] = o.ArkTxid
	}
	if !IsNil(o.CommitmentTxids) {
		toSerialize["commitmentTxids"] = o.CommitmentTxids
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	if !IsNil(o.IsPreconfirmed) {
		toSerialize["isPreconfirmed"] = o.IsPreconfirmed
	}
	if !IsNil(o.IsSpent) {
		toSerialize["isSpent"] = o.IsSpent
	}
	if !IsNil(o.IsSwept) {
		toSerialize["isSwept"] = o.IsSwept
	}
	if !IsNil(o.IsUnrolled) {
		toSerialize["isUnrolled"] = o.IsUnrolled
	}
	if !IsNil(o.Outpoint) {
		toSerialize["outpoint"] = o.Outpoint
	}
	if !IsNil(o.Script) {
		toSerialize["script"] = o.Script
	}
	if !IsNil(o.SettledBy) {
		toSerialize["settledBy"] = o.SettledBy
	}
	if !IsNil(o.SpentBy) {
		toSerialize["spentBy"] = o.SpentBy
	}
	return toSerialize, nil
}

type NullableVtxo struct {
	value *Vtxo
	isSet bool
}

func (v NullableVtxo) Get() *Vtxo {
	return v.value
}

func (v *NullableVtxo) Set(val *Vtxo) {
	v.value = val
	v.isSet = true
}

func (v NullableVtxo) IsSet() bool {
	return v.isSet
}

func (v *NullableVtxo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVtxo(val *Vtxo) *NullableVtxo {
	return &NullableVtxo{value: val, isSet: true}
}

func (v NullableVtxo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVtxo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


