/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OverwriteTopics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OverwriteTopics{}

// OverwriteTopics struct for OverwriteTopics
type OverwriteTopics struct {
		Topics []string `json:"topics,omitempty"`
}

// NewOverwriteTopics instantiates a new OverwriteTopics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOverwriteTopics() *OverwriteTopics {
	this := OverwriteTopics{}
	return &this
}

// NewOverwriteTopicsWithDefaults instantiates a new OverwriteTopics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOverwriteTopicsWithDefaults() *OverwriteTopics {
	this := OverwriteTopics{}
	return &this
}

// GetTopics returns the Topics field value if set, zero value otherwise.
func (o *OverwriteTopics) GetTopics() []string {
	if o == nil || IsNil(o.Topics) {
		var ret []string
		return ret
	}
	return o.Topics
}

// GetTopicsOk returns a tuple with the Topics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OverwriteTopics) GetTopicsOk() ([]string, bool) {
	if o == nil || IsNil(o.Topics) {
		return nil, false
	}
	return o.Topics, true
}

// HasTopics returns a boolean if a field has been set.
func (o *OverwriteTopics) HasTopics() bool {
	if o != nil && !IsNil(o.Topics) {
		return true
	}

	return false
}

// SetTopics gets a reference to the given []string and assigns it to the Topics field.
func (o *OverwriteTopics) SetTopics(v []string) {
	o.Topics = v
}

func (o OverwriteTopics) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OverwriteTopics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Topics) {
		toSerialize["topics"] = o.Topics
	}
	return toSerialize, nil
}

type NullableOverwriteTopics struct {
	value *OverwriteTopics
	isSet bool
}

func (v NullableOverwriteTopics) Get() *OverwriteTopics {
	return v.value
}

func (v *NullableOverwriteTopics) Set(val *OverwriteTopics) {
	v.value = val
	v.isSet = true
}

func (v NullableOverwriteTopics) IsSet() bool {
	return v.isSet
}

func (v *NullableOverwriteTopics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOverwriteTopics(val *OverwriteTopics) *NullableOverwriteTopics {
	return &NullableOverwriteTopics{value: val, isSet: true}
}

func (v NullableOverwriteTopics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOverwriteTopics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


