/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EstimateIntentFeeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EstimateIntentFeeRequest{}

// EstimateIntentFeeRequest struct for EstimateIntentFeeRequest
type EstimateIntentFeeRequest struct {
		Intent *Intent `json:"intent,omitempty"`
}

// NewEstimateIntentFeeRequest instantiates a new EstimateIntentFeeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEstimateIntentFeeRequest() *EstimateIntentFeeRequest {
	this := EstimateIntentFeeRequest{}
	return &this
}

// NewEstimateIntentFeeRequestWithDefaults instantiates a new EstimateIntentFeeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEstimateIntentFeeRequestWithDefaults() *EstimateIntentFeeRequest {
	this := EstimateIntentFeeRequest{}
	return &this
}

// GetIntent returns the Intent field value if set, zero value otherwise.
func (o *EstimateIntentFeeRequest) GetIntent() Intent {
	if o == nil || IsNil(o.Intent) {
		var ret Intent
		return ret
	}
	return *o.Intent
}

// GetIntentOk returns a tuple with the Intent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EstimateIntentFeeRequest) GetIntentOk() (*Intent, bool) {
	if o == nil || IsNil(o.Intent) {
		return nil, false
	}
	return o.Intent, true
}

// HasIntent returns a boolean if a field has been set.
func (o *EstimateIntentFeeRequest) HasIntent() bool {
	if o != nil && !IsNil(o.Intent) {
		return true
	}

	return false
}

// SetIntent gets a reference to the given Intent and assigns it to the Intent field.
func (o *EstimateIntentFeeRequest) SetIntent(v Intent) {
	o.Intent = &v
}

func (o EstimateIntentFeeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EstimateIntentFeeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Intent) {
		toSerialize["intent"] = o.Intent
	}
	return toSerialize, nil
}

type NullableEstimateIntentFeeRequest struct {
	value *EstimateIntentFeeRequest
	isSet bool
}

func (v NullableEstimateIntentFeeRequest) Get() *EstimateIntentFeeRequest {
	return v.value
}

func (v *NullableEstimateIntentFeeRequest) Set(val *EstimateIntentFeeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEstimateIntentFeeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEstimateIntentFeeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEstimateIntentFeeRequest(val *EstimateIntentFeeRequest) *NullableEstimateIntentFeeRequest {
	return &NullableEstimateIntentFeeRequest{value: val, isSet: true}
}

func (v NullableEstimateIntentFeeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEstimateIntentFeeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


