/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateStreamTopicsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateStreamTopicsResponse{}

// UpdateStreamTopicsResponse struct for UpdateStreamTopicsResponse
type UpdateStreamTopicsResponse struct {
		AllTopics []string `json:"allTopics,omitempty"`
		TopicsAdded []string `json:"topicsAdded,omitempty"`
		TopicsRemoved []string `json:"topicsRemoved,omitempty"`
}

// NewUpdateStreamTopicsResponse instantiates a new UpdateStreamTopicsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateStreamTopicsResponse() *UpdateStreamTopicsResponse {
	this := UpdateStreamTopicsResponse{}
	return &this
}

// NewUpdateStreamTopicsResponseWithDefaults instantiates a new UpdateStreamTopicsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateStreamTopicsResponseWithDefaults() *UpdateStreamTopicsResponse {
	this := UpdateStreamTopicsResponse{}
	return &this
}

// GetAllTopics returns the AllTopics field value if set, zero value otherwise.
func (o *UpdateStreamTopicsResponse) GetAllTopics() []string {
	if o == nil || IsNil(o.AllTopics) {
		var ret []string
		return ret
	}
	return o.AllTopics
}

// GetAllTopicsOk returns a tuple with the AllTopics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateStreamTopicsResponse) GetAllTopicsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllTopics) {
		return nil, false
	}
	return o.AllTopics, true
}

// HasAllTopics returns a boolean if a field has been set.
func (o *UpdateStreamTopicsResponse) HasAllTopics() bool {
	if o != nil && !IsNil(o.AllTopics) {
		return true
	}

	return false
}

// SetAllTopics gets a reference to the given []string and assigns it to the AllTopics field.
func (o *UpdateStreamTopicsResponse) SetAllTopics(v []string) {
	o.AllTopics = v
}

// GetTopicsAdded returns the TopicsAdded field value if set, zero value otherwise.
func (o *UpdateStreamTopicsResponse) GetTopicsAdded() []string {
	if o == nil || IsNil(o.TopicsAdded) {
		var ret []string
		return ret
	}
	return o.TopicsAdded
}

// GetTopicsAddedOk returns a tuple with the TopicsAdded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateStreamTopicsResponse) GetTopicsAddedOk() ([]string, bool) {
	if o == nil || IsNil(o.TopicsAdded) {
		return nil, false
	}
	return o.TopicsAdded, true
}

// HasTopicsAdded returns a boolean if a field has been set.
func (o *UpdateStreamTopicsResponse) HasTopicsAdded() bool {
	if o != nil && !IsNil(o.TopicsAdded) {
		return true
	}

	return false
}

// SetTopicsAdded gets a reference to the given []string and assigns it to the TopicsAdded field.
func (o *UpdateStreamTopicsResponse) SetTopicsAdded(v []string) {
	o.TopicsAdded = v
}

// GetTopicsRemoved returns the TopicsRemoved field value if set, zero value otherwise.
func (o *UpdateStreamTopicsResponse) GetTopicsRemoved() []string {
	if o == nil || IsNil(o.TopicsRemoved) {
		var ret []string
		return ret
	}
	return o.TopicsRemoved
}

// GetTopicsRemovedOk returns a tuple with the TopicsRemoved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateStreamTopicsResponse) GetTopicsRemovedOk() ([]string, bool) {
	if o == nil || IsNil(o.TopicsRemoved) {
		return nil, false
	}
	return o.TopicsRemoved, true
}

// HasTopicsRemoved returns a boolean if a field has been set.
func (o *UpdateStreamTopicsResponse) HasTopicsRemoved() bool {
	if o != nil && !IsNil(o.TopicsRemoved) {
		return true
	}

	return false
}

// SetTopicsRemoved gets a reference to the given []string and assigns it to the TopicsRemoved field.
func (o *UpdateStreamTopicsResponse) SetTopicsRemoved(v []string) {
	o.TopicsRemoved = v
}

func (o UpdateStreamTopicsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateStreamTopicsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AllTopics) {
		toSerialize["allTopics"] = o.AllTopics
	}
	if !IsNil(o.TopicsAdded) {
		toSerialize["topicsAdded"] = o.TopicsAdded
	}
	if !IsNil(o.TopicsRemoved) {
		toSerialize["topicsRemoved"] = o.TopicsRemoved
	}
	return toSerialize, nil
}

type NullableUpdateStreamTopicsResponse struct {
	value *UpdateStreamTopicsResponse
	isSet bool
}

func (v NullableUpdateStreamTopicsResponse) Get() *UpdateStreamTopicsResponse {
	return v.value
}

func (v *NullableUpdateStreamTopicsResponse) Set(val *UpdateStreamTopicsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateStreamTopicsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateStreamTopicsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateStreamTopicsResponse(val *UpdateStreamTopicsResponse) *NullableUpdateStreamTopicsResponse {
	return &NullableUpdateStreamTopicsResponse{value: val, isSet: true}
}

func (v NullableUpdateStreamTopicsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateStreamTopicsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


